## This rule redirects to an external API, signing requests with a secret
#[[redirects]]
#  from = "/"
#  to = "/index.html"
#  status = 200

#[[redirects]]
#from = "/portfolio"
#to = "/portfolio/index.html"
#status = 200
